### ISSUE TITLE
cic launch_singleton fails when using a fee

### ISSUE THREAD

**Issue by cmmarslender** [Chia-Network/internal-custody#36]
```
cic launch_singleton --fee 1000

Traceback (most recent call last):
  File "/Users/chrismarslender/Projects/internal-custody/venv/bin/cic", line 8, in <module>
    sys.exit(main())
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/cic/cli/main.py", line 1938, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/cic/cli/main.py", line 405, in launch_cmd
    asyncio.get_event_loop().run_until_complete(do_command())
  File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/cic/cli/main.py", line 377, in do_command
    await wallet_client.create_signed_transaction(
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/chia/rpc/wallet_rpc_client.py", line 230, in create_signed_transaction
    response: Dict = await self.fetch("create_signed_transaction", request)
  File "/Users/chrismarslender/Projects/internal-custody/venv/lib/python3.9/site-packages/chia/rpc/rpc_client.py", line 49, in fetch
    raise ValueError(res_json)
ValueError: {'error': '', 'success': False}
```

**Comment by cmmarslender** [comment]
works now
